### ISSUE TITLE
Add governance working group call 4 notes, video, deck

### ISSUE THREAD

**Issue by lrettig** [stacksgov/resources#19] opened 2020-03-18 18:37 UTC
We need to post notes for https://github.com/stacksgov/pm/issues/9

CC @whoabuddy

**Comment by lrettig** [comment] 2020-03-18 18:54
YouTube link: https://youtu.be/u8lZsVFCFtc

We still also need @dantrevino's slide deck.

Here are my raw notes from the call:

* Standups
    * Jason
        * GitHub getting more organized, resources are in the right places, please take a look at this if you haven't
        * We have some interesting issues going on e.g. icon for the Foundation/initiative
        * Another: where we’re going with some of these line items
        * good place for ppl to get more involved
        * want to make sure ppl are starring it, following it, getting notifications if they want them
        * next: want to get an issue template, figuring out flow of links (e.g., GH -> Forum, or v.v.), I want this flow to be easy for ppl, esp. those who aren’t as familiar with GH. we have a good system in place but want to improve this, e.g., project board not immediately visible - want to redirect ppl with good direction
    * Philip
        * been studying consequences of what we’ve been doing, can’t say I have a conclusion
        * good effort we’ve been doing, all of this is new, PoX is also new. we need to understand the scope. lots of literature we have to dig in. that’s one of the challenges to cope with, span of information and knowledge.
        * problems that have been discovered, issues in this field of work - esp. related to technical ways of abusing the system. let’s get to know if there’s something we can foresee how to prevent.
        * not just one person, everybody looking for sth, discover sth that’s a challenge, something we should record or share.
* Community survey
    * Philip: it’s ready to go, will bring us new understanding, new themes and subjects to dig into
    * Jason: aside from points I made in that forum post, I agree it’s good to go
    * Juliet: it’s a little long, we’ve all been through it, it’s not egregiously long, it’s time to put it out there and see what we can learn from the community
    * Roughly this set of ppl (~9) have answered it
    * Philip: if we get 30-40 ppl that will increase info.
    * Lane: do we want to record future results separately from our own? (rough consensus: no)
    * Jason: looking forward to seeing my answers alongside everyone else's
    * Jenny: we want to diversify the participants who are engaged in this - let’s talk more about this later
* Sharing interview notes
    * Does anyone have any strong thoughts or feelings on how these should be shared?
    * Jason: I’m pretty comfortable with putting my answers out there but been giving it a few days to let it sink in - so far I want to weigh on the side of open
    * Juliet: I think it’s up to the individual. If you’re given permission to put someone’s name on it, and they’re fine with that - if others don’t want this, becomes an issue of should you remove names from everything, titles, etc.
    * Lane: let’s keep it anonymous to protect everyone’s privacy. (De-anonymizing only some would make it easier to de-anonymize others.)
* Gov. proposal
    * Lane has been working on this for the past few days. Shared it with Brittany so far.
    * It’s sort of "all-inclusive” at the moment and may be simplified. Covers overall (non-stacks-specific) challenge in blockchain governance, as well as specific proposals for Foundation and broader ecosystem governance.
    * Includes preliminary findings from survey and one on one interviews.
    * Its contents were informed by the things I’ve learned from everyone in this group, on these calls, etc.
* DanT presentation
    * Put this together to help self understand
    * Hoping this helps the wider comm. get a simpler view of what gov. WG is doing, how thy can participate, things like that. Nothing spec. new here, pulled in info from Brittany’s forum post, these meetings, Juliet contributed.
    * Long-term I’ll yank out the questions. Focus of this is, what’s the state of gov.? What’s PBC doing? What does comm. need to do? What does this look like at the end?
    * It's not done yet
    * Want to give ppl a quick overview without their having to go to forum post, etc. - of timeframe
        * Foundation isn’t for fundraising, it’s for comm., and independent of PBC
        * Questions for the community - same set we talked about last week, nothing new here
        * We can pull these out and keep pointers to them
        * Blockstack comm.: involvement to decide on many of the gov. factors
        * Timeline is just a placeholder for now, need to update with real timelines
        * We want to give ppl an overview of how things are going - input into Foundation, creation, organization, etc.
        * After that, ongoing gov. input via some method, not defined yet
        * Some questions raised by the comm., by myself 
        * The key for me is the Blockstack Community slide - what’s the comm. doing, what’s our timeline. We can flesh this out with specific things to talk about
        * Also, PBC’s role - what are they doing, what have they done, what’s the timeframe
    * Juliet: I like the idea of a visual, consumable by the comm. It’s friendly, it’s easy to understand. Having accurate dates. Maybe a little more info later on as we start to surface these different questions that we have. Looking at e.g. principles of gov. for this comm.
    * There are definitely key questions we want to add here, foundational pieces. Make sure everyone’s on the same page about e.g. what’s the Stacks Foundation and how will it work?
    * Some of the more detailed questions don’t belong in this deck
    * Philip: They “why” of the Foundation is something people wonder about.
        * Would you mention the survey there too, as a way to have feedback on the ideas?
    * I didn’t call out Lane’s role in this, recommendations he’s providing and comm. feedback on that
    * About the “why” - that’s one of the things that drove me to put this together.
        * Is a Foundation the right org.? Why do we need it? That question is out there but PBC is already in the process of setting up a Foundation. That’s one of the disconnects that drove me to create this
    * Lane: let’s add this to the knowledge base
        * Can upload a PDF or link to it on slides.com
        * Dan: I’ll slap “draft” on it first, we need to update the dates
* Brittany update
    * There always has to be a disclaimer from PBC: this is a work in progress, not tradable info
    * The slowness in response is not because we’re not doing work behind the scenes, it’s because I need legal sign-off to publish things
    * I’ll go through the list of questions that are included in the GitHub (https://github.com/stacksgov/pm/issues/11)
        * Why do we want a Foundation? Who chose this?
            * In order for Blockstack to be “considered decentralized” no single person or entity is controlling the network. Right now PBC is biggest contributor to ecosystem so can be seen as a very centralized source of reliance, if PBC went away the network might not continue to exist
            * With framing in mind of making ecosystem more robust, resilient, decentralized, the plan is to spin out another entity that takes on some of the resp. that PBC has been doing to date - incl.:
                *  gov. of blockchain itself, how will decisions be made in the future? (SIP proposals). Currently SIPs are accepted via PBC engineers, by and large, that resp. will move into the new entity.
                * App Mining - rewards to ecosystem for developing apps - will also be part of the new entity. Rewards will continue to be distributed, system with which to do it will live outside PBC entity.
                * Miners, stacking, stakeholders important for security of ecosystem - those will also be supported through not just PBC but other ecosystem entities.
            * Our legal team looked at different structures. Non-profit structure is most common, alleviate pressure to create profit - supports ecosystem without being rent-seeking or trying to control the network
            * That’s why we think it’s a reasonable path
            * Within nonprofits there are multiple jurisdictions that are friendly to blockchain ecosystems - based on precedent: Singapore, USA, Switzerland.
                * In CH it’s called an assoc., in USA a “not for profit”, in SG a Foundation.
                * We looked at requirements, they’re fairly similar
                * But jurisdictions require members to be locally oriented, e.g., board of directors to be local in jurisdiction - CH, SG both require this.
                * Blockstack has a number of employees in US. We don’t have any key stakeholders in CH, but we do have active stakeholders in Asia incl. SG, so those two are the jurisdictions where we could help create this entity. We’ve been leaning towards SG foundation, has structural advantages for a global ecosystem - different requirements for board, members, how they can be set up.
                * This is how we arrived at SG Foundation.
            * Formation process can take 7 days - 2 months, because of approval on SG side.
                * Discussing internally, weighing different timelines
                * If we register and it takes two months it’s beyond our control but we’d rather have it in place sooner rather than later.
            * Within Foundation there are board members - think about gov. here
                * With SG Fnd., once entity incorporated - requires at least one board member - since Brittany will be heading up the foundation, she’ll be the first board member
                * Then local SG partner that’s active in stacks ecosystem will be the second
                * Those are required to set up the entity, but we can add additional board members after the entity has been set up. That will give us more time to implement gov. changes, comm. feedback, nominating members to weigh in on that process.
                * That may be a better solution rather than waiting until we have a fully-dev board to begin incorporating process, might take time
                * Looking at other structures - strong recommendation towards “MVP gov.” - clear pathways but not everything fully-baked when Foundation begins - we cannot anticipate all needs now
                * We need basics, make sure we can rep. needs of all stakeholders
                * So this is not a short term, two month process of figuring out all of the governance and shipping it. We need to put the minimum in place then aadd to it/enhance it over time.
            * e.g. App Mining - question about how this will look in the future - that will require some gov. and a lot of input - so we won’t have an exact answer in the next two weeks, but we want a path to figure this out as a foundation
        * How will it be funded?
            * PBC will either create a favorable loan, or will start with an initial donation to get operations up and running.
            * Long-term there are options, as foundation will take over portion of treasury. Could participate in stacking, use BTC there as source of funding
            * Looking at other projects: many use donation structure or loan structure. PBC needs to decide structurally, financially, tax-wise how that will work.
        * Managaging dev. work, data structures, etc. - don’t have answers to all of these right away but we’ll have a conversation about these
    * DanT: Any questions about structure or jurisdiction?
        * Why not name the “partner” in SG?
        * Is there already a defined org. structure for the board? E.g., terms, how comm. will have input into nomination/approval process, what decision-making process would look like.
            * It sounds like you have a plan, but we haven’t seen that plan. You’ve done a lot of work. All of us here have a lot of trust in PBC but there’s a missing piece of transparency. You’re talking about this stuff but there’s a lot going on that we/I didn’t know about.
            * What’s the plan?
    * Brittany: We have to be very mindful of announcing things and people trading on information, taking it as signals, some of the plan I’m communicating here has to be legally reviewed before w put it in writing. Not our intention to not be transparent but we’re walking a fine line - being as transparent as possible and not lock in decisions in advance but also we need more structure, a plan to see what’s feasible given how our entity is structured, legal and SEC requirements.
        * We’re now at a point where I can comm. these things with intention that not everything is decided and structurally none of it has gone into place yet, no one should count on it as truth until it’s confirmed
        * Partner in SG - there’s no formal paperwork - so not comfortable disclosing who they are yet.
        * How does the process/the board work? We have collected some basic gov. structures of boards which have generous ways to remove ppl from a board, and to add ppl. That’s where we want that MVP gov. If things need to change, it should be feasible, may not be perfect on launch but need to not be restricted in terms of time constraints.
    * Once foundation is set up I will no longer be employed by PBC, I’ll be employed by Foundation, so my role will change - but as of now I still work for PBC. So there’s encouragement to get the entity set up, so some things can be taken out of PBC.
* Jason proposal to extend call (https://github.com/stacksgov/pm/issues/12)
    * We have longer-form discussions on this call
    * But I also want to respect everyone’s time
    * Juliet: I think it’s a good idea, I’m glad you brought that up.
        * We can block 90 mins, don’t have to use the full time
        * There are some key questions that can be asked, as we are in the early stages of establishing the Foundation
        * We can schedule another call for this

**Comment by whoabuddy** [comment] 2020-03-18 19:57
My notes are below!

-----

# 20200311 Governance Call 4 Notes

## Quick round of intros

- consensus, we know each other, no intros needed

## What happened over the past week?

- usual things, recording shared
- stakeholders interviews continued
  - most of the people on the call
  - done 8 as of today, cleaning up notes, reviewing with interviewee
  - can discuss as later agenda item for how we want to use data
- survey out for review with our group
  - feedback was very helpful
  - a lot of things factored in from feedback
  - we are near the final version 

### Standup! Jason

- working on github resources
- encourage all to review and get notifications
- encourage all to look at and contribute issues

### Standup! Phillip

- as new things roll out, what is the scope of impact
- studying consequences of what we've been doing 
- cannot say he has a conclusion yet
- good effort we've been trying to do 
- understand scope of what we are doing
- a lot of literature we have to begin (dig in?)
- coping with span of information and knowledge

Lane: anything more specific?

- think of ways of using the systems
- working to foresee and prevent problems
- everyone is looking for something, discover the challenge or way to take advantage, we should record and share. our eyes working together.

Lane: broad knowledge of many different types of governance
- tying back to github resources, lots of info there
- maybe we need a "required reading" section
- throw info in as at least an issue to get it added

### Any other standups?

Dan: ready with slide deck

Brittany: ready with foundation info

Lane: let's stick to agenda order for now
- can change order through github issue in future

## Community Survey

Lane: updates he wanted to share higher on agenda then what others, apologies, will be more cognizant in the future.
- Thank you to everyone who took it, and for all of the feedback.

Phillip: it's ready to go! better to start doing something now.

Jason: my .02 is its ready outside my feedback

Lane: is it too long? any issues?

Phillip: not so long by the end, his feedback was for a lengthy experience originally but it got better.

Juliet: in agreement, it's time to put it out there. It's a little long but we've all been through it and its not aggregiously long - time to put it out there and learn from the community.

Lane: what does success look like? Is there a min number of responses? related question: what do we do with results? (or save that for another call)

_(silence - consensus?)_

Phillip: team here, 9 people in size

Lane: confirmed 7 responses, roughly our group has answered it

Phillip: if we get 3x our number, will increase the scope of information. 30 people, 180 people, how many people can answer? Maybe separate into two parts.

Lane: good question, do we want to clone the survey, record fresh answers to a broader audience?

Jason: no, I'm happy with my answers

Phillip: are partial answers registered? if someone doesn't finish?

Lane: yes, it is.

Lane: another question, how to share the results? directly from typeform, can export to google sheet, but moving on in the interest of time. Brittany, Jenny, any other specifics to share, or do that async?

Jenny: can do async, but let's talk about distribution strategy after initial phase of sharing.

Lane: can you elaborate?

Jenny: diversify participants engaged with it, can talk about it later.

Lane: keeping with the agenda, added a moment ago how to share interview notes

## Interview Notes 

Lane: questions about anonymity and privacy, people have been very honest, it would be easy to tell who the people are 

Jason: pretty ok with data being shared, leaning toward being open

Lane: should they be anonymous?

Juliet: should be up to the individual, then if someone doesn't want to be identified, how to modify data released.

Lane: inclination to leave it anonymous

Phillip: it has to be anonymous, serial one after another have patterns, way to organize are not all the answers together, only the ones that are serial. 

Lane: hang on, we are talking about the interviews not the survey, more concerned about details and lower number of responses

Lane: sounds like consensus, hoping to release in the next week 

## Preliminary governance proposal

Lane: one of his major deliverables, very rough draft shared with Brittany, liking to share with the whole community. Brittany, have you had a chance to review or any thoughts?

Brittany: circulating internally, think it's very good and comprehensive, should be able to share with community sooner to get feedback, could finish pass by the end of the day. overwhelming opinion very good, very comprehensive, might be able to pare it down (lots of background info about general community / where we are today). The second half is amazing, thanks for all the work on that. Can share it more broadly now, or get some more feedback then share with governance group.

Lane: exact shape is still being figured out, erred on the side of being very inclusive, talk about challenges of blockchain networks in general, later piece talks about specific ideas to governing a foundation, and governance of the entire ecosystem. Excited to share it with everyone, will do ASAP (hoping this week).

Lane: it's a bit of a brain dump, factors in a lot of things I've heard and learned from the calls, interviews, chat, and other outlets. Hoping people will agree their input is fed into this, and will be ample opportunity to weigh in. The next phase in his perspective.

## @dantrevino presentation on open questions

Lane: presentation on open questions about governance, update from brittany after that, 10min enough?

Dan: plenty.

A few weeks ago, had a bunch of questions trying to understand where we are, and where we are going. Put this together to help him understand, and hoping it will be used for the wider community to help people get a simple and more consumable view of what the group is doing, how to participate, and things like that.

Nothing specific to do here, pulled from Brittany's forum post, some of these meetings, Juliet contributed some questions (long-term, probably take those out). Focus: what's the state of governance? What is PBC doing? What does the community need to do? What does that look like at the end? How will it work together?

This is not done, but let's go through it.

Slide: Blockstack PBC laying groundwork for governance, basic description of what's going on, alternative to forum post and/or github.

Slide: An early vision, based on Brittany's forum post.

Slide: Questions for the community, can review later, from last calls.

Slide: Community side, our involvement to decide on things, another gantt chart and links to existing resources.

Note: timelines are placeholders for now, but gives a simple view that "this is what we are doing"

Slide: questions raised by the community (himself and others)

The key for him is the community slide, what we are doing, what our timeline is, resource links, as well as PBC's role, what are they doing, what have they done, and timelines.

Juliet: like the idea of a visual consumable by the community, friendly, easy to understand, having the dates are good, maybe a little more info. as we surface different questions we have, especially as we look at principles for governance, will want to add more.

Dan: yes, some more foundational pieces to add, how the foundation is going to work. He needed it for himself, and it will work for the community.

Phillip: the "why" of this foundation, one wonders, something we could add. are you thinking about publishing the survey results there?

Dan: didn't call out Lane's role in this, the "why" of the foundation is what drove him to put this together, foundational question is the foundation a right piece. why do we need it? is it necessary? yet we already have a process that's ongoing by PBC, so this disconnect was more to make sure the content was out there.

Lane: would love to see this on resources

Dan: currently on slides.com, we can link to it there, or pdf export available

Lane: let's move on to Brittany and her update

## Stacks Foundation (from PBC)

Slowness of response is not because aren't doing work behind the scenes, just that she needs more legal sign-offs before she can share any information.

Will go through the [list of questions](https://github.com/stacksgov/pm/issues/11) on Github to start.

__Q: High-level, why do we want a foundation, why choose this?__

For Blockstack to be considered decentralized, no signal person/entity controlling the network. Right now, Blockstack PBC is biggest contributor, so it can be seen as a centralized source of reliance. If Blockstack PBC went away, the network might not exist.

So with the framing of making things more robust, resilient, idea is to spin out another entity to do what Blockstack PBC is doing through today. Working on governance for the blockchain itself using SIPs (currently), accepted via Blockstack PBC engineers, so that responsibility will move into the new entity.

Program around app mining that gives rewards to the ecosystem, will also be part of new entity, so rewards will continue to be distributed. Will move it outside of the PBC entity.

As we increase capacity for miners, stakeholders in the ecosystem, will be supported by other entities and the ecosystem.

Based on that, legal team decided NPO is most common in blockchain projects, no burden to create profit from the ecosystem. There are multiple jurisdictions friendly to blockchain ecosystems, usually Singapore (foundation), USA (non-profit), and Switzerland (association).

Didn't want to use USA (lots of blockstack people here), no stakeholders in Switzerland, but lots in Asia / near Singapore. Leaning towards Singapore because it has a number of structural advantages for a global ecosystem like this.

That was the path to land on a Singapore-based foundation, process can take as little as 7 days, as long as 2 months because of approval process. Mindful of that on PBC side, exploring how to weigh those timelines. We don't know if we register and it ends up taking two months, out of our control, but would like to have it in place. That's the structural pieces we've been thinking about.

There are board members, advantages to Singapore, once we incorporate (requires 1 board member), since she is heading it she will likely be first board member. One singapore partner will be the second on board of directors, and fits requirement to form the entity. Can add more board members later, after implementing governance changes, so that the community can be involved in selection and weighing in opinions. Think this is better than waiting on a full board to set up the incorporation process.

Her research: talking to other projects about their successes, MVP governance recommended, how things can be decided, but everything might not be fully baked by the time foundation is started - we can't anticipate the needs this early on. Step 1 is getting it setup, Step 2 is adding more information (this is a long-term process, not a short one). An evolving process starting with the minimum.

Members of this call are aware of app mining, wondering how it will go in the future, we will not have an answer in the next 2 weeks on that specifically but want to have a path to work together.

Almost at time - looking through questions. How it will be funded. Initial thought: Blockstack PBC will create very favorable loan, or an initial donation, to get operations set up and running. Longer-term there are options since the foundation will take over a portion of the treasury of tokens, there may be room to participate in stacking or using bitcoin to fund operations.

Many peers in this space, set up with a donation structure or loan structure, haven't decided yet, up to PBC for how that will work structurally / financially / in terms of taxes.

We can have a more robust conversation in the interim term, but we don't have all those answers right away. Pause there, happy to jump in if any questions around short-term structure/jurisdiction.

Dan: Partner already in Singapore, someone already in mind, why not name that person/entity? Is there already an organizational structure for what the board would look like? Terms? How the community would have input to nomination / approval for folks? Decision making process?
- sounds like you have a plan, a lot of work has been done, but it feels like we haven't seen it. Feels like a missing piece of transparency, would like to see the actual plan.

Brittany: part of the behind-the-scenes planning is being very mindful of being a publicly-traded token, have to prevent people from taking that as signals. Can be put in writing, but has to be reviewed by the legal department, have to walk the fine line of being transparent and dealing with SEC approval. We are at a point where she can communicate these things that 1) not everything is decided and 2) nothing is in place yet, so don't count on info as truth.

Partner in Singapore, no formal paperwork of them coming on board, not comfortable disclosing as of yet. Other questions asked to the process, how the process works, how the board works, have collected some basic structures from other boards which have generous ways to add/remove people. Want that type of MVP governance so that if things ramp up and need to change, it will still be ok, but we cannot get it ready before launch and would rather launch now than be restricted by additional constraint.

Since she is an employee, she has to do this. Once foundation is setup, she will no longer be employed by Blockstack PBC, she will be employed by the foundation. This will change the relationship with her and the community. This is why there is encouragement to set the entity up to move things out of PBC. A little bit of an overlap.

Lane: time check, if you are free to stick around, can handle the host to someone else. he has a call, want to finish out the agenda. Should we do an AMA?

## Next/recurring call schedule

Lane: Jason proposed extending to 90min, maybe keep official at 60min with soft closing, people can stick around further.

Juliet: responding to Jason, think it's a good idea, glad we brought it up. We can always have it for 90 minutes, then if we don't go that far, oh well. To have that time today, there are key questions that can be asked even though we are at the early stage. Still some questions / discussion to be had. Might be a good idea to set another call to have those discussions. Rest of us can sit and talk about additional questions at this point.

Lane: that's a great idea, can block more call next week, or we can schedule a separate call depending on availability. strictly on call length, any other strong opinions?

Phillip: agree with Juliet.

Lane: no consensus yet, so no decision as of yet.

Juliet: everyone on call, please post your preference on github, want to get all involved.

## looking for other stewards

Lane: his own role in governance is evolving, and it should be, so he is a steward working hard to put things together to bootstrap, but there's no bottleneck. The same way PBC shouldn't be a centralized part of this, if he were gone tomorrow it should still function.

If you want to join the org on github, host a call, all meant to be open and permissionless. Open invitation the group.

## additional content

Jason: took over as host, open floor

Juliet: one of the key questions she has right now, public participation bit, understand there are early stages and the need to create a MVP of the foundation. Interested in how we as the community are making our voices heard and part of the decision-making process. Really important to her, that the people who want to be involved are able to be heard, and have their voice as part of the process. Don't see that now, but understand legal issues, perhaps things will be different if Brittany becomes the head of the foundation. less issues about legal ramifications re: PBC.

Community participation, since we now know app mining will be part of it, potential for stacking. Need more developers coming in, a lot interested in both app mining and stacking and the next steps with SIPs. Obviously, we need a little clarity, get more people involved, and more people to express themselves.

Dan: 100% agree with first part. To him, decisions around the organization, he sees app mining and other pieces talked about what the foundation would guide as secondary, not sure what the timeline is, for instance, i'd rather make sure we understand how the foundation is going to work, how it's going to make decisions, how we have input into that.

See things like we've got a foundation, we've got a decision making process, we've got a process for community input, now let's see how app mining v2 will work, or governance around the core development.

Brittany: First and foremost, set up the entity, set up structure to make independent decisions. Utilizing the process in place, then the secondary things will be strongly considered and decided on once the entity exists. The entity, set it up where everyone feels it can evolve.

Juliet: leaves the piece about the community being able to participate in this early foundation MVP, and how the community can contribute to decision making. the other piece about app mining she brought up, is only because she knows people are not as involved in governance now if they understood what going forward of the ramifications of the stacks foundation could be. not saying we should talk about app mining, or stacking, or anything else now - it's too early. important that the community can know where things are headed so we can provide more input.

Phillip: thinks that Brittany's report about was going on was very valuable, can understand things considered, happy that we have a way to have more time to define the details of governance. No pressure in the sense that we can bring up the MVP foundation then continue building the structure. In this presentation deck, Dan you could also add that part and the why, explain quite well why we have to bring up the org first to achieve more decentralization. (Sorry to add to your work load!) Would be very useful, think the attitude we have is very possible, very important.

Brittany: planning for next steps, have a draft of a lot of things covered on the call, will put something to format we can review and comment and weigh in. Kind of explained the path we are taking down, likely Singapore foundation, if strong concerns for or against can be heard, structure and decision-making process will be developed. Can compile info from other projects, talking to folks on ZCash board, other boards, as source of info for what they've learned and leveraging best practices. Few more of those calls today, would love to incorporate notes that she can share with us so it's as comprehensive as possible. Proposal on moving forward.

Dan: asking Brittany, discussion points going on, some uknowns to identify, to Juliet's points: can you also identify where the community input is going to come? To all of it? What decisions can the community provide input to, and what kind of things do you expect that are "just going to happen". Not trying to be accusatory, think we all have a ton of trust in PBC for general, but more to know what we can do and what we can spend time on, and to give a better idea of what's going on.

Brittany: very valid, good question, where does the community fit in? trying to gather from other projects, for example, from ZCash they have a number of board members, decided on, some more centralized and key players that represented parts of community, then helped create the board. filled more board members to profile they wanted to build. experience running a foundation, fill a seat for that. open source experience, fill a seat for that. seats were slotted and community had input on what the roles were and who was nominated. mainly feedback is that the process can be very complicated, how to combat nefarious players, and how do you work in a trusted environment where people way in, clear deliverables, clear decisions, without impeding the process. She sees that the benefit of MVP governance and where the community is involved. For example, ZCash set up committee not at a board level, but included stakeholders in the community who had a vote that was accepted based on majority, a little hierarchical but clear transparency across the board.

Can create gridlock, hoping to include in the notes as she talks to more places, recommend looking at the ZCash foundation and what they've done. Created a clear path and something similar we can adopt and our learn on. That will be inputted by the community.

Brittany: know we are 20min over, can continue in discord, excited to share more as we go along. thanks for the patience in communication.

**Closed** 2020-04-21 19:40 UTC
